# Generated by Django 4.0.5 on 2022-06-18 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Seller_app', '0001_initial'),
        ('User_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinformation',
            name='myuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_app.myuser'),
        ),
        migrations.AddField(
            model_name='productinformation',
            name='product_sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller_app.productsubcategory'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='product_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller_app.productinformation'),
        ),
    ]
