# Generated by Django 4.0.5 on 2022-06-18 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auction_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionQuery',
            fields=[
                ('auction_query_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_query', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CancelReport',
            fields=[
                ('cancel_report_id', models.IntegerField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('feedback_id', models.IntegerField(primary_key=True, serialize=False)),
                ('feedbackText', models.TextField()),
                ('rating', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SuccessReport',
            fields=[
                ('success_report_id', models.IntegerField(primary_key=True, serialize=False)),
                ('max_amt_bid', models.BigIntegerField()),
                ('is_sold', models.BooleanField()),
                ('auctiondetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auction_app.auctiondetails')),
                ('product_buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='Auction_app.bidder')),
            ],
        ),
    ]
